package com.sentimospadel.backend.notification.enums;

public enum PendingActionType {
    SUBMIT_MATCH_RESULT,
    CONFIRM_MATCH_RESULT,
    SUBMIT_TOURNAMENT_RESULT,
    CONFIRM_TOURNAMENT_RESULT,
    MATCH_FULL,
    MATCH_CANCELLED,
    MATCH_RESULT_CONFIRMED,
    MATCH_RESULT_REJECTED,
    TOURNAMENT_LAUNCHED,
    TOURNAMENT_RESULT_CONFIRMED,
    TOURNAMENT_RESULT_REJECTED,
    CLUB_BOOKING_APPROVED,
    CLUB_BOOKING_REJECTED,
    CLUB_VERIFICATION_APPROVED,
    CLUB_VERIFICATION_REJECTED
}
